language: rust

os:
  - linux

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - sudo apt-get update
  - sudo apt-get install -y llvm-3.9-dev libclang-3.9-dev clang-3.9

before_script:
  - rustup component add clippy

script:
  - cargo test --verbose
  - cargo clippy --all-targets --all-features -- -D warnings
