[workspace]
members = [
    ".",
    "examples/xed-min",
]

[package]
name = "xed-sys"
version = "0.2.0"
authors = ["Phantomical"]
edition = "2018"
publish = false

[dependencies]

[build-dependencies]
bindgen = "0.43"
fs_extra = "1.1"
num_cpus = "1.8"
target-lexicon = "0.2"
